# Generated by Django 4.2.5 on 2025-08-24 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('quantidade_estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TratamentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade usada no tratamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.produto')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.tratamento')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='clinica.produto')),
            ],
        ),
    ]
