# Generated by Django 4.2.5 on 2025-08-24 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_produto_tratamentoproduto_movimentacaoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade utilizada')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='clinica.agendamento', verbose_name='Agendamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.produto', verbose_name='Produto')),
            ],
        ),
        migrations.DeleteModel(
            name='TratamentoProduto',
        ),
    ]
