# Generated by Django 4.2.5 on 2025-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_consumoproduto_delete_tratamentoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='estoque_descontado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Estoque descontado?'),
        ),
    ]
