# Generated by Django 4.2.5 on 2025-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_agendamento_estoque_descontado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
