# Generated by Django 4.2.5 on 2025-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('data', 'hora'), name='unique_horario'),
        ),
    ]
